// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
const spec_identifier = {__proto__:null,program:10, if:16, else:22, while:26, repeat:30, times:34, end:36}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%pQ`QPOOPeOPOOOOQO'#Cp'#CpQ`QPOOOjQPO'#C`PoOSO'#C^POOO)C>i)C>iOOQO-E6n-E6nOwQPO,58zPOOO'#Co'#CoP!YOSO,58xPOOO,58x,58xOOQO'#Cf'#CfOOQO'#Cz'#CzOOQO'#Cq'#CqO!bQPO'#CbO!sQQO'#CcO!xQQO'#ChO!}QPO'#CjOOQO'#Cb'#CbOOQO1G.f1G.fPOOO-E6m-E6mPOOO1G.d1G.dOOQO-E6o-E6oOOQO,58|,58|O!TQPO,58}O!TQPO,59SO#SQPO,59UOwQPO1G.iOwQPO1G.nOwQPO1G.pO#XQPO7+$TOOQO7+$Y7+$YOOQO7+$[7+$[OwQPO<<GoOOQOAN=ZAN=Z",
  stateData: "#m~OPOSkOSlOShPQ~OTSO~OhTO~OmWO~OiXOjZO~OW`O]aO_bObcOm[O~OiXOjfO~OW`O]aO_bObhOm[O~OXiO~OXjO~O`kO~OanO~OZrOWVq]Vq_VqbVqmVq~O",
  goto: "#^oPPpPsPw!WPP!`P!WP!WPPPP!n!t!zPPPPPPPP#URUPTQORQdWQolQpmQqnRsr]]W_lmnr[]W_lmnrQliRmjQYTReYQRORVRY_WlmnrRg_]^W_lmnr",
  nodeNames: "⚠ SingleLineComment MultiLineComment CompilationUnit Program program Block If if Operator Call else While while Repeat repeat Number times end",
  maxTerm: 30,
  skippedNodes: [0,1,2,19],
  repeatNodeCount: 3,
  tokenData: "%c~R[YZw]^|pq!U!P!Q!^!Q!R#W!R![#]!c!}#e#T#]#e#]#^#s#^#b#e#b#c$i#c#o#e~|Ol~~!RPl~YZw~!ZPk~pq!U~!aQz{!g!P!Q!l~!lOh~~!qTP~OY!lZ]!l^;'S!l;'S;=`#Q<%lO!l~#TP;=`<%l!l~#]O`~~#bP`~!Q![#]Q#jRmQ!Q![#e!c!}#e#T#o#eU#xTmQ!Q![#e!c!}#e#T#g#e#g#h$X#h#o#eU$`RXSmQ!Q![#e!c!}#e#T#o#eU$nTmQ!Q![#e!c!}#e#T#c#e#c#d$}#d#o#eU%STmQ!Q![#e!c!}#e#T#h#e#h#i$X#i#o#e",
  tokenizers: [1, 2, new LocalTokenGroup("b~RPz{U~XP!P!Q[~aOj~~", 17, 25)],
  topRules: {"CompilationUnit":[0,3]},
  specialized: [{term: 29, get: value => spec_identifier[value] || -1}],
  tokenPrec: 0
})
