// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  SingleLineComment = 1,
  MultiLineComment = 2,
  CompilationUnit = 3,
  Program = 4,
  Block = 6,
  If = 7,
  Operator = 9,
  Call = 10,
  While = 12,
  Repeat = 14,
  Number = 16
