name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Build
      run: |
        cd client
        npm install
        npm run build -- karel --configuration production
        npm run build -- karel-evaluation --configuration production
        npm run build -- application --configuration production
        cd projects
        cd karel
        npm install
        npm run build
        cd ..
        cd karel-evaluation
        npm install
        npm run build
        cd ../..
        
    - name: Test
      run: |
        npm run test -- --browsers=ChromeHeadless
        
