name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Build
      run: |
        cd client
        npm install
        npm run ci:build -- application
        npm run ci:build -- karel
        npm run ci:build -- karel-evaluation
        
    - name: Test
      run: |
        cd client
        npm install
        npm run ci:test
        
