name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Restore client dependencies
      run: |
        cd client
        npm install
    - name: Build client
      run: |
        cd client
        npm run build -- karel --configuration production
        npm run build -- karel-evaluation --configuration production
        npm run build -- application --configuration production
        cd projects
        cd karel
        npm install
        npm run build
        cd ..
        cd karel-evaluation
        npm install
        npm run build
        cd ../..
    - name: Test client
      run: |
        cd client
        npm run test -- --browsers=ChromeHeadless
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore server dependencies
      run: |
        cd server
        dotnet restore
    - name: Build server
      run: |
        cd server
        dotnet build --no-restore
    - name: Test server
      run: |
        cd server
        dotnet test --no-build --verbosity normal
        
